# File Name: makefile.test
# Author: Sunny Taksande
# Date: 27 June 2011
# Purpose: makefile for building test application for
#          uart communicaton.

# Set appropriate paths

INSTALLDIR	= ../console
PROJECTPATH	= .
TESTAPPPATH	= $(PROJECTPATH)/test
BINPATH		= $(PROJECTPATH)/bin
TARGETPATH	= $(BINPATH)

TARGETS		= $(TARGETPATH)/test

SRCFILES 	= $(TESTAPPPATH)/test.c

DEPENDANCIES	= makefile.test \
		$(INSTALLDIR)/include/uart.h
		 
# Compilation Flags

CC		=/media/_home/aurion/ruiva-dm355-dvsdk2/montavista/pro/devkit/arm/v5t_le/bin/arm_v5t_le-gcc 
CFLAGS		=  
INCLUDEFLAGS    = -I $(INSTALLDIR)/include
LIBFLAGS        = -L $(INSTALLDIR)/lib -luart

# Compilation Section

all: $(TARGETS)

$(TARGETPATH)/test: $(DEPENDANCIES) $(SRCFILES)
	$(CC) $(CFLAGS) $(SRCFILES) $(INCLUDEFLAGS) $(LIBFLAGS) -o $@

# Cleaning Section

clean:
	rm -f $(TARGETS)
